reports/bampfa/bampfaCollectionsWorksheet.jrxml
Committing a change to Collections Worksheet (made back in December)
=> BAMPFA-343

datasources/ucjeps/ucjepsMetadataV2.sql
Reverts cspace-deployment/Tools#82
=> Revert "UCJEPS-543: attempt to remove tabs from previous determinations"

datasources/bampfa/bampfa_collectionitems_vw.sql, functions/bampfa/get_first_blobcsid.sql
Add fields to bampfa_collectionitems_vw and function
utils.get_first_blobcsid
=> BAMPFA-402 bampfa_collectionitems_vw

reports/pahma/HsrPhaseOneInventory.jrxml
=> Added JIRA Pahma-1311 jrxml file

reports/pahma/SystematicInventoryHSR.jrxml
This is to transport the report Michael has changed, listed in PAHMA-1325.
=> Updated SystematicInventoryHSR.jrxml report as instructed in PAHMA-1325

reports/iReportBestPractice.txt, reports/pahma/HsrPhaseOneInventory.jrxml
I have downloaded and put in Michael's update to report HsrPhaseOne.jrxml. I have also updated the iReportsBestPractice.txt with more detailed steps based on the process I did to get the previous .jrxml deployed.
=> PAHMA-1325: HSR Systematic Inventory report sometimes truncates object numbers

qa-webapp-tests/features/README.md, qa-webapp-tests/features/botgarden_imaginator.feature, qa-webapp-tests/features/botgarden_ireports.feature, qa-webapp-tests/features/botgarden_landing.feature, qa-webapp-tests/features/botgarden_search.feature, qa-webapp-tests/features/pahma_imagebrowser.feature, qa-webapp-tests/features/pahma_imageserver.feature, qa-webapp-tests/features/pahma_imaginator.feature, qa-webapp-tests/features/pahma_ireports.feature, qa-webapp-tests/features/pahma_landing.feature, qa-webapp-tests/features/pahma_search.feature, qa-webapp-tests/features/pahma_suggest.feature, qa-webapp-tests/features/step_definitions/eloan_steps.rb, qa-webapp-tests/features/step_definitions/environment.rb, qa-webapp-tests/features/step_definitions/imagebrowser_steps.rb, qa-webapp-tests/features/step_definitions/imageserver_steps.rb, qa-webapp-tests/features/step_definitions/imaginator_steps.rb, qa-webapp-tests/features/step_definitions/ireports_steps.rb, qa-webapp-tests/features/step_definitions/landing_steps.rb, qa-webapp-tests/features/step_definitions/search_steps.rb, qa-webapp-tests/features/step_definitions/suggest_steps.rb, qa-webapp-tests/features/support/rails_helper.rb, qa-webapp-tests/features/ucjeps_eloan.feature, qa-webapp-tests/features/ucjeps_imageserver.feature, qa-webapp-tests/features/ucjeps_landing.feature, qa-webapp-tests/features/ucjeps_publicsearch.feature, qa-webapp-tests/features/ucjeps_search.feature
Git was giving us trouble by treating the features directory as a submodule that lost its remote tracking. I had to rm the directory and replace it again, but this time it works now!
=> Fixed up strange git error, this is DJAN-37: Automating Tests for webapps

reports/cinefiles/cinefilesWorkDupTitles.jrxml
Replaced SQL in cinefilesWorkDupTitles report.
=> BAMPFA-374 fix SQL in Dup Titles report

qa-webapp-tests/features/bampfa_search.feature, qa-webapp-tests/features/botgarden_search.feature, qa-webapp-tests/features/pahma_internal.feature, qa-webapp-tests/features/pahma_search.feature, qa-webapp-tests/features/step_definitions/ireports_steps.rb, qa-webapp-tests/features/step_definitions/search_steps.rb, qa-webapp-tests/features/support/env.rb, qa-webapp-tests/features/ucjeps_publicsearch.feature, qa-webapp-tests/features/ucjeps_search.feature
Minor changes to xxx_search.feature and ucjeps_publicsearch.feature:
1. steps to mark & unmark checkboxes (pixonly, locsonly)
2. check footer (e.g. "Current time: ")
3. check sign out behavior of ucjeps publicsearch
=> UCJEPS-486: added more tests for publicsearch

scripts/pahma/hierarchies/object_location/CreateObjectPlaceLocationTable.sql
Refactored (e.g., create table as); corrected name of function; corrected field referenced in one index.
=> PAHMA-1363

functions/bampfa/get_mediumjpeg_filepath.sql
Updated function, get_mediumjpeg_filepath, to use path to blobs on
managed server.
=> BAMPFA-472

datasources/bampfa/bampfa_website_extract.sh
Updated shell script to create 30-day and 7-day versions of website
extract
=> BAMPFA-351

scripts/pahma/batch_barcode/reloadxml.sh
New script, reloadxml.sh, to reload tricoder XML files that failed to
load correctly.
=> PAHMA-1351

datasources/bampfa/bampfa_website_extract.sql, functions/bampfa/get_updatedat_co_mh.sql
Develop script to get most recent timestamp from cataloging AND related
MH records.  Incorporate into shell script that calls the SQL.
=> BAMPFA-496

scripts/dynamic-converter/README.md, scripts/dynamic-converter/sql-dynamic-parser.py
In these commits, Cesar and I:
- Added a check for "urn%" entries after the database changes.
- Clarified error messages, and cleaned up script (deleted commented out code, added descriptive comments).
- Moved the generation of counts statements so that it only occurs after a terms list is found.
- Wrote a descriptive README file that documents are progress from the beginning.
=> PAHMA-1519: Added more SQL checks and documentation

datasources/ucjeps/ucjepsMetadata.sql
=> UJ-35: country, state, and country displaynames now extract from refnames

scripts/cinefiles/checkBlobs.py
=> CF-4: repair MD5 query for blobs due to 'new Nuxeo'

datasources/ucjeps/ucjepsMetadata.sql
from country, state, county refnames (when they appear as refNames after S2D conversion)
=> UJ-35: revise Solr ETL query to extract display names

scripts/csops/csstatus
https://jira.ets.berkeley.edu/jira/browse/CC-349
=> add csstatus

scripts/csops/cscheckmemnew, scripts/csops/csheapdump, scripts/csops/cspid
=> Adding new memcheck and heapdump

scripts/csops/csautorestart
https://jira.ets.berkeley.edu/jira/browse/CC-374
=> Adding csautorestart.

functions/bampfa/concatArtistNatl.sql, functions/botgarden/get_actiondate.sql, functions/botgarden/get_deaddate.sql
get_actiondate, get_deaddate for BotGarden All Accessions Ever report
concatArtistNatl for BAMPFA Collection from Search report
=> CC-531, CC-703: new functions for new reports

scripts/csops/csheapdump, scripts/csops/csservname
Note that this will break the tools for tomcat 7 based deployments.
=> Modifying tools to work with tomcat 8 based deployments.
